# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad393418b1558d004c122c7e29e7ba18be20f06ebf6b7a5d6215287bad31cb53b31067844f621f0898cd5057795944d63f7ba8ccabbd72d2ebc5ffc7a309404e

test:
  secret_key_base: de09c39d3a5e3d6cc94e039b314199371bacc925ed13ddb82a9406498c3ee9681b2f33bf9015a219463cb6e47c52922242ffabc5959d32d50be6781804500ec1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
